### PR TITLE
more details on the event payload from the BZ DB schema v3.14+

### PR DESCRIPTION
**Pull request by franck-boullier**
@kaihendry merge if this is OK for you

### CODE REVIEW

**Comment by kaihendry** [comment]
I have no idea how to tell what's changed for my [events I am testing with](https://github.com/unee-t/lambda2sns/tree/master/tests/events) or how to review this.

**Comment by kaihendry** [comment]
Oh I see the files now. They don't appear to be valid JSON.

**Comment by franck-boullier** [comment]
> They don't appear to be valid JSON.

Any suggestion/pointer on what might be wrong?

**Comment by kaihendry** [comment]
https://s.natalian.org/2018-06-14/json.mp4

**Comment by kaihendry** [comment]
tl;dr remove the comments otherwise i can't merge. I could do this for you.

Comments like these are not permitted in JSON:

```
# The formats are
#	notification_type -> varchar(255)
#	bz_source_table -> varchar(240)
#	notification_id -> varchar(255)
#	created_datetime -> datetime
#	unit_id -> smallint(6)
#	case_id -> mediumint(9)
#	case_title -> varchar(255)
#	reporter_user_id -> mediumint(9)
```

Furthermore since your procedure SQL doesn't seem to treat integer types correctly, i.e. you quote them, currently at the `/api/db-change-message/process` API that ingests these payloads, I am assuming every field is a string at first. Then I am looking at the example to work out if I need to parseInt.

**Comment by franck-boullier** [comment]
> remove the comments otherwise i can't merge

@kaihendry: done

**Comment by kaihendry** [comment]
`"current_list_of_invitees": "13, 15, 23"` should be `"current_list_of_invitees": [13, 15, 23]` but I understand it can be hard to stringify JSON correctly from SQL. So my code will be making some assumptions of the string payloads.

**Comment by kaihendry** [comment]
I only just noticed **assignee_user_id** has been renamed? This is [breaking the code](https://github.com/unee-t/frontend/blob/master/imports/api/rest/post-process-db-change-message.js#L38). WHY???
```

case_assignee_updated.json:     "assignee_user_id": "19",
case_assignee_updated.json:     "old_case_assignee_user_id": "12",
case_assignee_updated.json:     "new_case_assignee_user_id": "19",
case_new.json:  "old_case_assignee_user_id": "12",
case_new.json:  "new_case_assignee_user_id": "12",
case_new_message.json:  "old_case_assignee_user_id": "12",
case_new_message.json:  "new_case_assignee_user_id": "21",
case_updated.json:      "old_case_assignee_user_id": "12",
case_updated.json:      "new_case_assignee_user_id": "12",
case_user_invited.json: "old_case_assignee_user_id": "12",
case_user_invited.json: "new_case_assignee_user_id": "20",

```

**Comment by franck-boullier** [comment]
>I only just noticed assignee_user_id has been renamed (...) WHY???

@kaihendry this is to avoid confusion when the assignee is changed (who is the assigned person?).
Having both values:
- old assignee
- new assignee

allows us to knowingly choose who we want to send the notification to

**Pull request merged**
